import type { Metadata } from "next";
import { Geist, Geist_Mono, Urbanist } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/providers/theme-provider"
import { Header } from "@/components/navigation/header"
import { Footer } from "@/components/navigation/footer"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Toaster } from "sonner"

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-sans",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={urbanist.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative scroll-smooth antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <ScrollArea className="h-screen">{children}</ScrollArea>
          <Footer />
          <Toaster position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  )
}
